# Generated by Django 3.2.9 on 2022-01-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_code', models.CharField(max_length=50)),
                ('short_url', models.CharField(max_length=50)),
                ('long_url', models.CharField(max_length=50)),
                ('clicked_times', models.IntegerField(default=0)),
            ],
        ),
    ]
