# Generated by Django 3.2.9 on 2022-01-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220121_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='long',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='site',
            name='short',
            field=models.URLField(blank=True, null=True),
        ),
    ]
