# Generated by Django 4.0.1 on 2022-02-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_site_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='short',
            field=models.URLField(blank=True, null=True),
        ),
    ]
