name: Django CI

env:
  USER: postgres
  PASSWORD: postgres
  DATABASE_NAME: postgres
  HOST_URL: http://127.0.0.1:8000/
  BASE_URL: http://127.0.0.1:8000/
  DSN: ${{ secrets.DSN }}
  PORT: 5432
  DEBUG: 0
  SECRET_KEY: ${{ secrets.SECRET_KEY }}


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      postgres_main:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
          PORT: 5432
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Migrations
      run: python manage.py migrate
    - name: Code Coverage
      run: coverage run --source='api' manage.py test api
    - name: Get Coverage Report
      run: | 
        coverage report
        coverage xml
    - name: Send code coverage to codecov
      run:  |
        curl -Os https://uploader.codecov.io/latest/linux/codecov 
        chmod +x codecov
        ./codecov
